// <auto-generated />
namespace ATM_management_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class databases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databases));
        
        string IMigrationMetadata.Id
        {
            get { return "202306301204371_databases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
